var champs = [
  'Aatrox',
  'Ahri',
  'Akali',
  'Alistar',
  'Amumu',
  'Anivia',
  'Annie',
  'Ashe',
  'Aurelion Sol',
  'Azir',
  'Bard',
  'Blitzcrank',
  'Brand',
  'Braum',
  'Caitlyn',
  'Camille',
  'Cassiopeia',
  'Cho\'Gath',
  'Corki',
  'Darius',
  'Diana',
  'Dr. Mundo',
  'Draven',
  'Ekko',
  'Elise',
  'Evelynn',
  'Ezreal',
  'Fiddlesticks',
  'Fiora',
  'Fizz',
  'Galio',
  'Gangplank',
  'Garen',
  'Gnar',
  'Gragas',
  'Graves',
  'Hecarim',
  'Heimerdinger',
  'Illaoi',
  'Irelia',
  'Ivern',
  'Janna',
  'Jarvan IV',
  'Jax',
  'Jayce',
  'Jhin',
  'Jinx',
  'Kalista',
  'Karma',
  'Karthus',
  'Kassadin',
  'Katarina',
  'Kayle',
  'Kayn',
  'Kennen',
  'Kha\'Zix',
  'Kindred',
  'Kled',
  'Kog\'Maw',
  'LeBlanc',
  'Lee Sin',
  'Leona',
  'Lissandra',
  'Lucian',
  'Lulu',
  'Lux',
  'Malphite',
  'Malzahar',
  'Maokai',
  'Master Yi',
  'Miss Fortune',
  'Mordekaiser',
  'Morgana',
  'Nami',
  'Nasus',
  'Nautilus',
  'Nidalee',
  'Nocturne',
  'Nunu',
  'Olaf',
  'Orianna',
  'Ornn',
  'Pantheon',
  'Poppy',
  'Quinn',
  'Rakan',
  'Rammus',
  'Rek\'Sai',
  'Renekton',
  'Rengar',
  'Riven',
  'Rumble',
  'Ryze',
  'Sejuani',
  'Shaco',
  'Shen',
  'Shyvana',
  'Singed',
  'Sion',
  'Sivir',
  'Skarner',
  'Sona',
  'Soraka',
  'Swain',
  'Syndra',
  'Tahm Kench',
  'Taliyah',
  'Talon',
  'Taric',
  'Teemo',
  'Thresh',
  'Tristana',
  'Trundle',
  'Tryndamere',
  'Twisted Fate',
  'Twitch',
  'Udyr',
  'Urgot',
  'Varus',
  'Vayne',
  'Veigar',
  'Vel\'Koz',
  'Vi',
  'Viktor',
  'Vladimir',
  'Volibear',
  'Warwick',
  'Wukong',
  'Xayah',
  'Xerath',
  'Xin Zhao',
  'Yasuo',
  'Yorick',
  'Zac',
  'Zed',
  'Ziggs',
  'Zilean',
  'Zoe',
  'Zyra'
];
var champion = champs[Math.floor(Math.random() * champs.length)];
function changeChamp() {
  champion = champs[Math.floor(Math.random() * champs.length)];
  if (champion == "Aatrox") {
    document.body.style.backgroundImage = "url('assets/aatrox.png')";
  } else if (champion == "Ahri") {
    document.body.style.backgroundImage = "url('assets/ahri.png)";
  } else if (champion == "Akali") {
    document.body.style.backgroundImage = "url('assets/akali.png)";
  } else if (champion == "Alistar") {
    document.body.style.backgroundImage = "url('assets/alistar.png)";
  } else if (champion == "Alistar") {
    document.body.style.backgroundImage = "url('assets/alistar.png)";
  } else if (champion == "Amumu") {
    document.body.style.backgroundImage = "url('assets/amumu.png)";
  } else if (champion == "Anivia") {
    document.body.style.backgroundImage = "url('assets/anivia.png)";
  } else if (champion == 'Annie') {
    document.body.style.backgroundImage = "url('assets/annie.png')";;
  }
}
setInterval(function() {
  document.getElementById("champname").innerHTML = champion;
});
